apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - name: publisher
        image: ulaj/publisher-service:latest
        ports:
        - containerPort: 5005
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
