apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: ulaj/subscriber-service:latest
        ports:
        - containerPort: 5007
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
